### PR TITLE
Enable Gradle Build Scans

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
See https://scans.gradle.com/

With this addition we will have the possibility to access and share detailed information about the build process of Alpha, such as duration of build phases, an overview of dependencies, etc. To get an idea, check out a build scan from this PR's source branch: https://scans.gradle.com/s/j7kqgasr5a7am

### CODE REVIEW

**Comment by AntoniusW** [comment]
This is a nice idea, but I have some concerns regarding privacy, since some information about the local machine gets published.  We should be sure that this automated publishing only occurs on the CI servers (or if explicitly requested).
As far as I understand, the build now checks whether the environment variable `CI` is defined and then always publishes. Since `CI` also enables the extensive test suite, this is not the best flag for making sure that the build actually runs on the CI server. Is there some way we can be sure to not run on anyones personal computer?

**Comment by lorenzleutgeb** [comment]
Sure. I will remove the trigger via the environment variable `CI` and instead add the explicit command line flag `--scan` to `.travis.yml`. This way, the possibility that someone sets the environment variable for another purpose and then ends up having information uploaded is completely eliminated.

**Comment by AntoniusW** [comment]
Seems reasonable now.
Are there any other opinions from the team? @rtaupe @madmike200590 ?

**Comment by rtaupe** [comment]
> 
> 
> Seems reasonable now.
> Are there any other opinions from the team? @rtaupe @madmike200590 ?

Sounds good!

**Pull request merged**
