### PR TITLE
Link to "A coder's guide to answer set programming" from README.md

### PR DESCRIPTION
**Pull request by madmike200590**
I've recently gotten around to get started on my "side-side-"project of writing a beginner-friendly guide on ASP and have been publishing my results via github pages [here](https://madmike200590.github.io/asp-guide/). The guide is still very much a work in progress and is going to grow significantly, both in terms of quantity as well as quality, but I think the tutorial as it is now might already be useful.

I'd like to reference the guide from Alpha's `README.md` in order to give people an easily digestible starting point for learning ASP.

### CODE REVIEW

**Review by AntoniusW — APPROVED** [review]

**Comment by AntoniusW** [comment]
@madmike200590 The guide is a great addition! Is there a way to comment on the guide or suggest changes to it?

**Comment by lorenzleutgeb** [comment]
Great idea!

> Is there a way to comment on the guide or suggest changes to it?

@AntoniusW I guess you could open a PR at https://github.com/madmike200590/asp-guide :)

I thought about doing something similar, but to use something like an "interactive notebook" for examples. Like a Jupyter Notebook, or [Nextjournal](https://nextjournal.com/) where the "code cells" contain ASP code that evaluates to answer sets. The user could then (right on the website) modify the code cell and see how that changes the output. Going even further, one could visualize the in-/output, e.g. color a graph. Lots of work, but cool! :)

**Comment by madmike200590** [comment]
> @madmike200590 The guide is a great addition! Is there a way to comment on the guide or suggest changes to it?

Yes, exactly like @lorenzleutgeb said, just make a fork of https://github.com/madmike200590/asp-guide, edit the markdown sources and open a PR.
The deployment as github page is configured in the repo settings, so you can have your fork deployed to a separate URL as well for preview and testing. Github pages in the simplest config has jekyll behind it for html generation. I'll probably switch that over to [mdBook](https://rust-lang.github.io/mdBook/) at some point, but wanted to stay with the most straightforward option for the beginning.

**Comment by AntoniusW** [comment]
Thank you for pointing me in the right direction, @lorenzleutgeb and @madmike200590.

**Pull request merged**
