### PR TITLE
Solver Heuristics

### PR DESCRIPTION
**Pull request by rtaupe**
New heuristics to steer the solver through the search space:

- BerkMin
- BerkMinLiteral
- DependencyDrivenHeuristic (in several variants defined by BodyActivityType)
- GeneralizedDependencyDrivenHeuristic (in several variants defined by BodyActivityType)
- AlphaActiveRuleHeuristic
- AlphaHeadMustBeTrueHeuristic

Adaptions in several places were necessary to ease development of the new heuristics.

### CODE REVIEW

**Comment by rtaupe** [comment]
Note: Current CI build fails are due to resource-intensive unit tests (cf. https://discuss.gradle.org/t/gradle-check-fails-but-tests-finish-with-success/10214). On my system, tests succeed. Will disable some resource-intensive test cases.

**Comment by lorenzleutgeb** [comment]
FYI I closed and reopened this PR to trigger a build on Travis CI. Sorry for the noise.

**Comment by rtaupe** [comment]
@lorenzleutgeb OK thanks. I´ve also tried to trigger the build, without success

**Comment by lorenzleutgeb** [comment]
After transferring the repository from `AntoniusW` to `alpha-asp` the [Integration Settings](https://github.com/alpha-asp/Alpha/settings/hooks/9268486) needed manual adjustments I just applied in the order of minutes ago. Probably it did not work out for you because the settings were still bogus at the time. Everything should be smooth now. :)

**Pull request merged**
